[package]
name = "halo"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
lazy_static = "1.5.0"
num-bigint = {version = "0.4.6", features = ["rand"]}
num-traits = "0.2.19"
itertools = "0.14.0"
